### ISSUE TITLE
greenkeeper

### ISSUE THREAD

**Issue by mattiaerre** [opencomponents/oc-registry-graphql-express-middleware#3]
# Description

not sure how to enable it; help needed

**Comment by matteofigus** [comment]
I enabled it for all the repos already in the opencomponents organisation. You can edit the settings yourself and view the docs by going to Settings > Integrations. Still, it looks to me that all is setup correctly so I don't understand why the badge says that it's disabled...

**Comment by mattiaerre** [comment]
@matteofigus maybe the next push/PR will fix? let me try

**Comment by mattiaerre** [comment]
@matteofigus still no joy 😞 what can we do next?

**Comment by matteofigus** [comment]
Looks green now @mattiaerre  :)

**Comment by mattiaerre** [comment]
Thank you @matteofigus
